/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedDocumentsIndexRouteImport } from './routes/_authed/documents.index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedDocumentsNewRouteImport } from './routes/_authed/documents.new'
import { Route as AuthedDocumentsDocumentIdRouteImport } from './routes/_authed/documents.$documentId'
import { Route as AuthedAdminApiKeysRouteImport } from './routes/_authed/admin/api-keys'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/admin/users.index'
import { Route as AuthedAdminDocumentsIndexRouteImport } from './routes/_authed/admin/documents.index'
import { Route as AuthedAdminUsersNewRouteImport } from './routes/_authed/admin/users.new'
import { Route as AuthedAdminUsersUserIdRouteImport } from './routes/_authed/admin/users.$userId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentsIndexRoute = AuthedDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedDocumentsNewRoute = AuthedDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentsDocumentIdRoute =
  AuthedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminApiKeysRoute = AuthedAdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminDocumentsIndexRoute =
  AuthedAdminDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminUsersNewRoute = AuthedAdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminUsersUserIdRoute = AuthedAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/profile': typeof AuthedProfileRoute
  '/admin/api-keys': typeof AuthedAdminApiKeysRoute
  '/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/documents/new': typeof AuthedDocumentsNewRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/documents/': typeof AuthedDocumentsIndexRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/users/new': typeof AuthedAdminUsersNewRoute
  '/admin/documents/': typeof AuthedAdminDocumentsIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthedProfileRoute
  '/admin/api-keys': typeof AuthedAdminApiKeysRoute
  '/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/documents/new': typeof AuthedDocumentsNewRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/documents': typeof AuthedDocumentsIndexRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/users/new': typeof AuthedAdminUsersNewRoute
  '/admin/documents': typeof AuthedAdminDocumentsIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/admin/api-keys': typeof AuthedAdminApiKeysRoute
  '/_authed/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/_authed/documents/new': typeof AuthedDocumentsNewRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/documents/': typeof AuthedDocumentsIndexRoute
  '/_authed/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/_authed/admin/users/new': typeof AuthedAdminUsersNewRoute
  '/_authed/admin/documents/': typeof AuthedAdminDocumentsIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin'
    | '/profile'
    | '/admin/api-keys'
    | '/documents/$documentId'
    | '/documents/new'
    | '/admin/'
    | '/documents/'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/documents/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/profile'
    | '/admin/api-keys'
    | '/documents/$documentId'
    | '/documents/new'
    | '/admin'
    | '/documents'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/documents'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/profile'
    | '/_authed/admin/api-keys'
    | '/_authed/documents/$documentId'
    | '/_authed/documents/new'
    | '/_authed/admin/'
    | '/_authed/documents/'
    | '/_authed/admin/users/$userId'
    | '/_authed/admin/users/new'
    | '/_authed/admin/documents/'
    | '/_authed/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents/': {
      id: '/_authed/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthedDocumentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/documents/new': {
      id: '/_authed/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthedDocumentsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents/$documentId': {
      id: '/_authed/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/api-keys': {
      id: '/_authed/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthedAdminApiKeysRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/documents/': {
      id: '/_authed/admin/documents/'
      path: '/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AuthedAdminDocumentsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/users/new': {
      id: '/_authed/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthedAdminUsersNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/users/$userId': {
      id: '/_authed/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminApiKeysRoute: typeof AuthedAdminApiKeysRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminUsersUserIdRoute: typeof AuthedAdminUsersUserIdRoute
  AuthedAdminUsersNewRoute: typeof AuthedAdminUsersNewRoute
  AuthedAdminDocumentsIndexRoute: typeof AuthedAdminDocumentsIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminApiKeysRoute: AuthedAdminApiKeysRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminUsersUserIdRoute: AuthedAdminUsersUserIdRoute,
  AuthedAdminUsersNewRoute: AuthedAdminUsersNewRoute,
  AuthedAdminDocumentsIndexRoute: AuthedAdminDocumentsIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedDocumentsDocumentIdRoute: typeof AuthedDocumentsDocumentIdRoute
  AuthedDocumentsNewRoute: typeof AuthedDocumentsNewRoute
  AuthedDocumentsIndexRoute: typeof AuthedDocumentsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedDocumentsDocumentIdRoute: AuthedDocumentsDocumentIdRoute,
  AuthedDocumentsNewRoute: AuthedDocumentsNewRoute,
  AuthedDocumentsIndexRoute: AuthedDocumentsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
